#!/usr/bin/env bash
#
# Deploy nxtsmarthome.com.au.
#
# Production runs on THIS host from this directory: nginx proxies
# nxtsmarthome.com.au to nxtsmarthome-com-au.service (`next start`,
# 127.0.0.1:3013). Pages revalidate from Strapi on their own (ISR), so a deploy
# is only needed for code, catalogue or config changes, not for new posts.
#
#   ./deploy.sh                build the working tree, swap it in, restart
#   ./deploy.sh --pull         git pull --ff-only first
#   ./deploy.sh --allow-dirty  build with uncommitted changes
#
# The build goes into .next-build while the live server keeps serving .next.
# Only after a successful build is the service stopped, the directories
# swapped, and the service started: seconds of downtime, and a failed build
# never touches the live site. Building into a side directory also avoids the
# bestlooking.skin failure where a running server regenerated ISR pages into the
# .next a build was writing, linking the previous build's CSS.
#
# The swap is reversed automatically if the new build does not come up healthy.

set -euo pipefail
cd "$(dirname "$0")"

UNIT=nxtsmarthome-com-au.service
PORT=3013
PULL=0; ALLOW_DIRTY=0
for a in "$@"; do
  case "$a" in
    --pull) PULL=1 ;;
    --allow-dirty) ALLOW_DIRTY=1 ;;
    *) echo "unknown flag: $a" >&2; exit 2 ;;
  esac
done

export NVM_DIR=/root/.nvm
# shellcheck disable=SC1091
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm use 22 >/dev/null
export NODE_OPTIONS=--max-old-space-size=2048

[ "$PULL" = 1 ] && git pull --ff-only

if [ -n "$(git status --porcelain --untracked-files=no)" ] && [ "$ALLOW_DIRTY" = 0 ]; then
  echo "working tree is dirty -- commit, or pass --allow-dirty" >&2
  git status --short --untracked-files=no >&2
  exit 1
fi

# Sitemap before, for IndexNow: only URLs that are new or whose lastmod changed
# are submitted afterwards.
SITEMAP_BEFORE=$(mktemp); SITEMAP_AFTER=$(mktemp); CHANGED=$(mktemp)
trap 'rm -f "$SITEMAP_BEFORE" "$SITEMAP_AFTER" "$CHANGED"' EXIT
curl -s -m 20 "http://127.0.0.1:$PORT/sitemap.xml" -o "$SITEMAP_BEFORE" || true

rm -rf .next-build
# tsconfig includes .next/types, the live build's route type stubs. They only
# serve type-checking, and they go stale once a route is deleted, which fails
# the new build's type check. The running server does not read them.
rm -rf .next/types
# lib/strapi.ts throws if Strapi is unreachable, so a CMS outage fails the build
# here instead of publishing a site with no articles.
if ! NEXT_DIST_DIR=.next-build npm run build; then
  echo "build failed -- the live site was not touched" >&2
  exit 1
fi

swap_in() {
  sudo systemctl stop "$UNIT"
  rm -rf .next-prev
  [ -d .next ] && mv .next .next-prev
  mv .next-build .next
  sudo systemctl start "$UNIT"
}
roll_back() {
  echo "rolling back to the previous build" >&2
  sudo systemctl stop "$UNIT"
  rm -rf .next-failed; mv .next .next-failed
  mv .next-prev .next
  sudo systemctl start "$UNIT"
}

healthy() {
  local code href css
  for _ in $(seq 1 30); do
    sleep 2
    code=$(curl -s -o /dev/null -w '%{http_code}' -m 20 "http://127.0.0.1:$PORT/" || true)
    [ "$code" = "200" ] || continue
    # Every stylesheet the home page links must exist, or the site renders unstyled
    # while every status check says 200.
    for href in $(curl -s -m 20 "http://127.0.0.1:$PORT/" | grep -o '/_next/static/css/[a-z0-9]*\.css' | sort -u); do
      css=$(curl -s -o /dev/null -w '%{http_code}' -m 20 "http://127.0.0.1:$PORT$href" || true)
      [ "$css" = "200" ] || { echo "MISSING stylesheet: $href -> $css" >&2; return 1; }
    done
    return 0
  done
  return 1
}

swap_in
if ! healthy; then
  echo "new build is not healthy -- check: journalctl -u ${UNIT%.service} -n 50" >&2
  [ -d .next-prev ] && roll_back
  exit 1
fi
rm -rf .next-prev .next-failed

# nginx reads the 301 map from public/_redirects.map, regenerated by prebuild.
sudo nginx -t -q && sudo systemctl reload nginx

curl -s -m 20 "http://127.0.0.1:$PORT/sitemap.xml" -o "$SITEMAP_AFTER" || true
node -e '
  const fs = require("fs");
  const parse = (f) => { const m = new Map(); const x = fs.readFileSync(f, "utf8");
    for (const u of x.matchAll(/<url>([\s\S]*?)<\/url>/g)) {
      const loc = (u[1].match(/<loc>(.*?)<\/loc>/) || [])[1];
      const mod = (u[1].match(/<lastmod>(.*?)<\/lastmod>/) || [])[1] || "";
      if (loc) m.set(loc, mod);
    } return m; };
  const before = parse(process.argv[1]), after = parse(process.argv[2]);
  const changed = [...after].filter(([loc, mod]) => before.get(loc) !== mod).map(([loc]) => new URL(loc).pathname);
  fs.writeFileSync(process.argv[3], changed.join("\n"));
' "$SITEMAP_BEFORE" "$SITEMAP_AFTER" "$CHANGED" || true
node scripts/submit-indexnow.mjs "$CHANGED" || echo "IndexNow submission failed (deploy is fine)" >&2

echo "deployed: $(git log --oneline -1)"
